Repository CA-G12/GeekSchool, pull requests merged in 2022-10, with the labels that each got.

#2 File structure
  .eslintrc.json
  .gitignore
  client/.eslintrc.json
  client/.gitignore
  client/README.md
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/public/manifest.json
  client/src/App.tsx
  client/src/assets/.gitkeep
  client/src/components/.gitkeep
  client/src/context/.gitkeep
  client/src/index.tsx
  client/src/pages/.gitkeep
  client/src/react-app-env.d.ts
  client/src/utils/.gitkeep
  client/tsconfig.json
  package-lock.json
  package.json
  server/__test__/index.test.js
  server/app.ts
  server/controllers/index.ts
  server/database/index.ts
  server/index.ts
  server/middlewares/index.ts
  server/models/index.ts
  server/queries/index.ts
  server/routes/index.ts
  server/utils/index.ts
  tsconfig.json
Labels: done

#13 Created the database connection.
  .example.env
  package.json
  server/config/environment.ts
  server/database/connection.ts
  server/database/index.ts
Labels: awaiting-review

#11 create server
  package-lock.json
  package.json
  server/app.ts
  server/index.ts
  server/routes/index.ts
Labels: awaiting-review

#18 Create user auth middleware
  server/middlewares/userAuth.ts
  server/utils/CustomError/index.ts
  server/utils/index.ts
  server/utils/interfaces/index.ts
  server/utils/interfaces/requestInterface.ts
  server/utils/jwt/index.ts
Labels: awaiting-review

#17 add fake data
  server/database/seed/announcements.json
  server/database/seed/assignmentStudent.json
  server/database/seed/assignments.json
  server/database/seed/classStudent.json
  server/database/seed/classes.json
  server/database/seed/feedbacks.json
  server/database/seed/health.json
  server/database/seed/parents.json
  server/database/seed/questions.json
  server/database/seed/recommendations.json
  server/database/seed/reports.json
  server/database/seed/schedules.json
  server/database/seed/students.json
  server/database/seed/teachers.json
  server/database/seed/testStudent.json
  server/database/seed/tests.json
  server/database/seed/users.json
Labels: done

#14 create models
  package-lock.json
  package.json
  server/models/announcement.ts
  server/models/assignment.ts
  server/models/assignmentStudent.ts
  server/models/class.ts
  server/models/classStudent.ts
  server/models/feedback.ts
  server/models/health.ts
  server/models/index.ts
  server/models/parent.ts
  server/models/question.ts
  server/models/recommendation.ts
  server/models/report.ts
  server/models/schedule.ts
  server/models/student.ts
  server/models/teacher.ts
  server/models/test.ts
  server/models/testStudent.ts
  server/models/user.ts
Labels: done

#19 [POST]/auth/logout
  server/controllers/auth/index.ts
  server/controllers/auth/logout.ts
  server/controllers/index.ts
  server/routes/auth.ts
  server/routes/index.ts
Labels: done

#22 auth-context
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/context/AuthContext/index.tsx
  client/src/interfaces/index.ts
  client/src/interfaces/userInterface.ts
  client/tsconfig.json
Labels: done

#27 26 teacherauth middleware
  server/middlewares/teacherAuth.ts
  server/utils/interfaces/requestInterface.ts
Labels: Approved

#24 21 build seed bd
  .eslintrc.json
  package.json
  server/database/build.ts
  server/database/seed.ts
  server/database/seed/classes.json
  server/database/seed/health.json
  server/database/seed/index.ts
  server/database/seed/questions.json
  server/database/seed/students.json
  server/database/seed/teachers.json
  server/database/seed/users.json
  server/models/index.ts
  server/models/student.ts
  server/models/teacher.ts
  server/models/test.ts
Labels: awaiting-review

#25 parent auth middle-ware
  client/src/context/AuthContext/index.tsx
  server/middlewares/parentAuth.ts
  server/utils/interfaces/requestInterface.ts
Labels: awaiting-review

#29 28 auth route
  server/controllers/auth/index.ts
  server/controllers/auth/userData.ts
  server/controllers/index.ts
  server/middlewares/index.ts
  server/middlewares/userAuth.ts
  server/routes/auth.ts
Labels: Approved

#20 Create signup route
  .eslintrc.json
  client/src/context/.gitkeep
  jest.config.ts
  nodemon.json
  package-lock.json
  server/__test__/auth.test.ts
  server/__test__/index.test.ts
  server/app.ts
  server/controllers/auth/index.ts
  server/controllers/auth/signup.ts
  server/controllers/errors/404.ts
  server/controllers/errors/500.ts
  server/controllers/errors/index.ts
  server/controllers/index.ts
  server/database/build.ts
  server/middlewares/userAuth.ts
  server/queries/index.ts
  server/queries/parentQueries.ts
  server/queries/studentQueries.ts
  server/queries/teacherQueries.ts
  server/queries/userQueries.ts
  server/routes/auth.ts
  server/utils/CustomError/index.ts
  server/utils/index.ts
  server/utils/interfaces/index.ts
  server/utils/interfaces/payloadInterface.ts
  server/utils/interfaces/userRequestInterface.ts
  server/utils/interfaces/userTabelInterface.ts
  server/utils/interfaces/userValInterface.ts
  server/utils/jwt/index.ts
  server/utils/validation/index.ts
  server/utils/validation/parentValidation.ts
  server/utils/validation/userValidation.ts
  tsconfig.json
Labels: done

#50 [GET] class/classId/announcment
  package-lock.json
  server/__test__/auth.test.ts
  server/__test__/classRoute.test.ts
  server/controllers/class/getAnnouncement.ts
  server/controllers/index.ts
  server/database/connection.ts
  server/database/seed.ts
  server/middlewares/index.ts
  server/middlewares/studentAndTeacher.ts
  server/middlewares/userAuth.ts
  server/models/student.ts
  server/queries/class/getAnnouncementQuery.ts
  server/queries/class/index.ts
  server/routes/class.ts
  server/routes/index.ts
Labels: Approved

#59 49 create login route
  package.json
  server/__test__/login.test.ts
  server/controllers/auth/index.ts
  server/controllers/auth/login.ts
  server/controllers/index.ts
  server/database/build.ts
  server/database/seed.ts
  server/queries/index.ts
  server/queries/loginQuery.ts
  server/routes/auth.ts
  server/utils/index.ts
  server/utils/interfaces/auth.ts
  server/utils/interfaces/index.ts
  server/utils/jwt/index.ts
  server/utils/validation/index.ts
  server/utils/validation/loginValidate.ts
Labels: done

#69 60 create get students route in class
  server/__test__/classRoute.test.ts
  server/controllers/class/getClassQuestions.ts
  server/controllers/class/getClassStudents.ts
  server/controllers/class/index.ts
  server/controllers/index.ts
  server/queries/class/getClassStudents.ts
  server/queries/class/index.ts
  server/queries/index.ts
  server/routes/class.ts
Labels: done

#77 62 create update question route in class
  server/__test__/putAnswerQuestion.test.ts
  server/controllers/class/index.ts
  server/controllers/class/putAnswerQuestion.ts
  server/controllers/index.ts
  server/queries/class/getClassStudentsQuery.ts
  server/queries/class/index.ts
  server/queries/class/putQuestionQuery.ts
  server/queries/index.ts
  server/routes/class.ts
  server/utils/index.ts
  server/utils/interfaces/index.ts
  server/utils/interfaces/queryInterfaces.ts
  server/utils/validation/index.ts
  server/utils/validation/putAnswerQuestionValidate.ts
Labels: done, BACK-END

#79 63 create add announcment route in class
  server/__test__/addAnnouncement.test.ts
  server/controllers/class/addAnnouncement.ts
  server/controllers/class/index.ts
  server/controllers/index.ts
  server/database/seed/announcements.json
  server/queries/class/addAnnouncementQuery.ts
  server/queries/class/index.ts
  server/queries/index.ts
  server/routes/class.ts
  server/utils/index.ts
  server/utils/interfaces/index.ts
  server/utils/interfaces/queryInterfaces.ts
  server/utils/validation/addAnnouncementValidate.ts
  server/utils/validation/index.ts
Labels: done, BACK-END

#74 get all student who submit tasks
  server/__test__/classRoute.test.ts
  server/controllers/class/getAllStudentHowSubmitTasks.ts
  server/controllers/class/putAssignmentTeacher.ts
  server/controllers/index.ts
  server/database/seed/assignmentStudent.json
  server/models/assignmentStudent.ts
  server/queries/class/getStudentTasksQuery.ts
  server/queries/class/index.ts
  server/queries/index.ts
  server/routes/class.ts
Labels: done

#71 create update assignment route and test it
  server/__test__/classRoute.test.ts
  server/controllers/class/index.ts
  server/controllers/class/putAssignmentStudent.ts
  server/controllers/class/putAssignmentTeacher.ts
  server/controllers/index.ts
  server/middlewares/index.ts
  server/middlewares/studentAuth.ts
  server/queries/class/index.ts
  server/queries/class/putAssignmentStudentQuery.ts
  server/queries/class/putAssignmentTeacherQuery.ts
  server/routes/class.ts
  server/utils/interfaces/index.ts
  server/utils/interfaces/updateAssignmentPayloadInterface.ts
  server/utils/interfaces/updateGradPayloadInterface.ts
  server/utils/validation/index.ts
  server/utils/validation/updateAssignmentPayloadValidate.ts
  server/utils/validation/updateGradPayloadValidate.ts
Labels: done

#76 56 delete assignment
  server/__test__/deleteAssignment.test.ts
  server/__test__/login.test.ts
  server/controllers/class/deleteAssignment.ts
  server/controllers/class/index.ts
  server/controllers/index.ts
  server/queries/class/deleteAssignment.ts
  server/queries/class/index.ts
  server/queries/index.ts
  server/routes/class.ts
Labels: done, BACK-END

#75 54 get assignments
  server/__test__/getAssignment.test.ts
  server/controllers/class/getAnnouncement.ts
  server/controllers/class/getAssignments.ts
  server/controllers/class/index.ts
  server/controllers/index.ts
  server/database/seed/assignmentStudent.json
  server/database/seed/assignments.json
  server/middlewares/studentAndTeacher.ts
  server/queries/class/index.ts
  server/queries/class/studentAssignmentQuery.ts
  server/queries/class/teacherAssignmentQuery.ts
  server/queries/index.ts
  server/routes/class.ts
Labels: done, BACK-END

#65 Created the class statistics route.
  package-lock.json
  package.json
  server/__test__/auth.test.ts
  server/__test__/class.test.ts
  server/__test__/classRoute.test.ts
  server/__test__/index.test.ts
  server/controllers/auth/signup.ts
  server/controllers/class/addAnnouncement.ts
  server/controllers/class/deleteAssignment.ts
  server/controllers/class/getAllStudentHowSubmitTasks.ts
  server/controllers/class/getAssignments.ts
  server/controllers/class/getClassQuestions.ts
  server/controllers/class/getClassStudents.ts
  server/controllers/class/getStats.ts
  server/controllers/class/index.ts
  server/controllers/class/putAnswerQuestion.ts
  server/controllers/index.ts
  server/database/build.ts
  server/database/seed/assignmentStudent.json
  server/database/seed/assignments.json
  server/database/seed/classStudent.json
  server/database/seed/classes.json
  server/database/seed/feedbacks.json
  server/database/seed/health.json
  server/database/seed/parents.json
  server/database/seed/questions.json
  server/database/seed/recommendations.json
  server/database/seed/reports.json
  server/database/seed/schedules.json
  server/database/seed/students.json
  server/database/seed/teachers.json
  server/database/seed/testStudent.json
  server/database/seed/tests.json
  server/database/seed/users.json
  server/middlewares/studentAndTeacher.ts
  server/middlewares/studentAuth.ts
  server/middlewares/teacherAuth.ts
  server/middlewares/userAuth.ts
  server/models/student.ts
  server/models/test.ts
  server/queries/class/classStats.ts
  server/queries/class/index.ts
  server/queries/index.ts
  server/queries/userQueries.ts
  server/routes/class.ts
  server/routes/index.ts
  server/utils/interfaces/userTabelInterface.ts
  server/utils/validation/parentValidation.ts
Labels: done

#68 Created remove student from class route.
  package.json
  server/__test__/deleteStudentClass.test.ts
  server/controllers/class/deleteStudentFromClass.ts
  server/controllers/class/index.ts
  server/controllers/index.ts
  server/queries/class/deleteStudentQuery.ts
  server/queries/class/index.ts
  server/queries/index.ts
  server/routes/class.ts
  server/utils/index.ts
  server/utils/validation/deleteStudentFromClassValidation.ts
  server/utils/validation/index.ts
Labels: done

#66 post questions
  server/__test__/classRoute.test.ts
  server/controllers/class/getAllStudentWhoSubmitTasks.ts
  server/controllers/class/index.ts
  server/controllers/class/postQuestion.ts
  server/controllers/index.ts
  server/queries/class/index.ts
  server/queries/class/postQuestionQuery.ts
  server/routes/class.ts
  server/utils/index.ts
  server/utils/interfaces/index.ts
  server/utils/interfaces/queryInterfaces.ts
  server/utils/validation/index.ts
  server/utils/validation/postQuestionValidate.ts
Labels: awaiting-review

#70 Created add new feedback route.
  server/__test__/addNewFeedback.test.ts
  server/controllers/class/addNewFeedback.ts
  server/controllers/class/index.ts
  server/controllers/index.ts
  server/database/seed/feedbacks.json
  server/middlewares/index.ts
  server/queries/class/addNewFeedback.ts
  server/queries/class/index.ts
  server/queries/index.ts
  server/routes/class.ts
  server/utils/index.ts
  server/utils/interfaces/addNewFeedbackInterface.ts
  server/utils/interfaces/index.ts
  server/utils/validation/addNewFeedbackValidation.ts
  server/utils/validation/index.ts
Labels: done

#67 Created the class feedback review.
  server/__test__/classFeedback.test.ts
  server/controllers/class/getFeedback.ts
  server/controllers/class/index.ts
  server/controllers/index.ts
  server/queries/class/getClassFeedbackQuery.ts
  server/queries/class/index.ts
  server/queries/index.ts
  server/routes/class.ts
Labels: done

#78 Created dashboard component
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/assets/.gitkeep
  client/src/assets/Logo.png
  client/src/assets/avatar.png
  client/src/components/.gitkeep
  client/src/components/Class/Class.tsx
  client/src/components/Class/ClassDashboard/ClassDashboard.css
  client/src/components/Class/ClassDashboard/ClassDashboard.tsx
  client/src/components/StatsDummy/Dummy.tsx
  client/src/i18n/config.js
  client/src/i18n/locales/ar/translations.json
  client/src/i18n/locales/en/translations.json
  package.json
Labels: done

#73 Created add new assingment route.
  server/__test__/addNewAssignment.test.ts
  server/controllers/class/addNewAssignment.ts
  server/controllers/class/index.ts
  server/controllers/index.ts
  server/queries/class/addNewAssignmentQuery.ts
  server/queries/class/index.ts
  server/routes/class.ts
  server/utils/index.ts
  server/utils/validation/index.ts
  server/utils/validation/newAssignmentValidation.ts
Labels: done

#81 57 post recommendation
  server/__test__/postRecommendation.test.ts
  server/controllers/class/index.ts
  server/controllers/class/postRecommendation.ts
  server/controllers/class/recommended.ts
  server/controllers/index.ts
  server/database/seed/recommendations.json
  server/queries/class/index.ts
  server/queries/class/postRecommendation.ts
  server/queries/index.ts
  server/routes/class.ts
  server/utils/index.ts
  server/utils/interfaces/index.ts
  server/utils/interfaces/recommendationInterface.ts
  server/utils/validation/index.ts
  server/utils/validation/recommendationValidation.ts
Labels: done, BACK-END

#82 58 post test
  server/__test__/postTest.test.ts
  server/controllers/class/index.ts
  server/controllers/class/postTest.ts
  server/controllers/class/recommended.ts
  server/controllers/index.ts
  server/database/seed/testStudent.json
  server/database/seed/tests.json
  server/queries/class/getClassStudentsQuery.ts
  server/queries/class/index.ts
  server/queries/class/postTestQuery.ts
  server/queries/index.ts
  server/routes/class.ts
  server/utils/index.ts
  server/utils/interfaces/index.ts
  server/utils/interfaces/testInterface.ts
  server/utils/validation/index.ts
  server/utils/validation/testValidation.ts
Labels: done, BACK-END

#90 86 create announcement card
  client/src/components/Class/cards/AnnouncementCard.tsx
  client/src/components/Class/cards/index.ts
  client/src/components/Class/cards/style.css
  client/src/interfaces/componentsInterface.tsx
  client/src/interfaces/index.ts
Labels: done

#96 95 assignment card
  client/src/components/assignmentCard/StudentAssignmentCard.tsx
  client/src/components/assignmentCard/TeacherAssignmentCard.tsx
  client/src/components/assignmentCard/index.css
  client/src/components/assignmentCard/index.tsx
Labels: done, FRONT-END

#39 23 create signup page
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/index.tsx
  client/src/components/signUpForm/AddChild.tsx
  client/src/components/signUpForm/ParentSignUp.tsx
  client/src/components/signUpForm/StudentSignUp.tsx
  client/src/components/signUpForm/TeacherSignUp.tsx
  client/src/components/signUpForm/index.tsx
  client/src/interfaces/index.ts
  client/src/interfaces/userInterface.ts
  client/src/pages/.gitkeep
  client/src/pages/index.tsx
  client/src/pages/signUp/index.tsx
  client/src/pages/signUp/style.css
  client/src/style.css
  client/src/validations/index.tsx
  client/src/validations/userValidation.tsx
  package-lock.json
Labels: awaiting-review

#89 85 create feedbackquestionsrecommended cards components
  client/public/index.html
  client/src/components/FeedbackCard.tsx
  client/src/components/QuestionsCard.tsx
  client/src/components/RecommendedCard.tsx
  client/src/components/index.tsx
  client/src/components/style.css
  client/src/interfaces/componentsInterface.ts
  client/src/interfaces/componentsInterface.tsx
  client/src/interfaces/index.ts
Labels: awaiting-review

#83 [GET] class grade
  server/__test__/classRoute.test.ts
  server/controllers/class/getClassGrades.ts
  server/controllers/class/index.ts
  server/controllers/index.ts
  server/database/seed/assignments.json
  server/database/seed/testStudent.json
  server/database/seed/tests.json
  server/queries/class/getClassGradesQuery.ts
  server/queries/class/index.ts
  server/queries/index.ts
  server/routes/class.ts
Labels: done, BACK-END, route

#92 question page: /class/questions
  client/src/App.tsx
  client/src/components/Class/ClassDashboard/ClassDashboard.tsx
  client/src/components/Class/Questions/AnsweredQuestion.tsx
  client/src/components/Class/Questions/Question.tsx
  client/src/components/Class/Questions/index.tsx
  client/src/components/Class/Questions/style.css
  client/src/components/Class/index.tsx
  client/src/context/AuthContext/index.tsx
  server/__test__/classRoute.test.ts
  server/controllers/class/getClassQuestions.ts
  server/database/seed/questions.json
  server/queries/class/getClassQuestionsQuery.ts
Labels: awaiting-review, FRONT-END

#80 Created add new test modal.
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/ClassTests/AddTest/AddTest.css
  client/src/components/ClassTests/AddTest/AddTest.tsx
  client/src/components/ClassTests/ClassTests.tsx
Labels: awaiting-review

#103 99 edit class layout
  client/src/components/AsideLink.tsx
  client/src/components/Class/ClassDashboard/ClassDashboard.css
  client/src/components/Class/ClassDashboard/ClassDashboard.tsx
  client/src/components/Class/ClassDashboard/style.css
  client/src/components/Class/index.tsx
  client/src/style.css
Labels: awaiting-review

#53 51 login page front end
  client/src/App.tsx
  client/src/context/AuthContext/index.tsx
  client/src/pages/index.tsx
  client/src/pages/login/index.tsx
  package-lock.json
  package.json
Labels: awaiting-review, FRONT-END

#93 grades page: /class/grades
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/Class/ClassDashboard/ClassDashboard.tsx
  client/src/components/Class/Grades/NameCell.tsx
  client/src/components/Class/Grades/ResultCell.tsx
  client/src/components/Class/Grades/handleData.ts
  client/src/components/Class/Grades/index.tsx
  client/src/components/Class/Grades/style.css
  client/src/components/Class/Questions/index.tsx
  client/src/components/Class/StudentsPage/style.css
  server/__test__/profile.test.ts
  server/controllers/profiles/getTeachersClasses.ts
  server/database/seed/assignmentStudent.json
  server/database/seed/assignments.json
  server/database/seed/classStudent.json
  server/database/seed/testStudent.json
Labels: done

#127 Created get classes for student route.
  server/__test__/getStudentClasses.test.ts
  server/controllers/index.ts
  server/controllers/student/getStudentClasses.ts
  server/controllers/student/index.ts
  server/database/seed/classes.json
  server/middlewares/studentAuth.ts
  server/models/class.ts
  server/queries/index.ts
  server/queries/student/getStudentClassesQuery.ts
  server/queries/student/index.ts
  server/routes/index.ts
  server/routes/student.ts
Labels: awaiting-review

#121 Created the route for getting the parent information.
  client/src/components/Class/Assignments/Assignments.css
  client/src/components/Class/Assignments/Assignments.tsx
  client/src/components/Class/ClassDashboard/ClassDashboard.tsx
  client/src/components/Class/cards/AssignmentCards.css
  client/src/components/Class/cards/StudentAssignmentCard.tsx
  client/src/components/Class/cards/TeacherAssignmentCard.tsx
  client/src/components/Class/cards/index.ts
  client/src/components/ClassFeedback/ClassFeedback.css
  client/src/components/ClassFeedback/ClassFeedback.tsx
  client/src/components/assignmentCard/index.tsx
  server/__test__/getParentInfo.test.ts
  server/controllers/class/getAssignments.ts
  server/controllers/parent/getParentInfo.ts
  server/controllers/parent/index.ts
  server/queries/class/studentAssignmentQuery.ts
  server/queries/class/teacherAssignmentQuery.ts
  server/queries/index.ts
  server/queries/parent/getParentInfoQuery.ts
  server/queries/parent/index.ts
  server/routes/index.ts
  server/routes/parent.ts
Labels: awaiting-review

#126 Created the get teacher's students route.
  client/package-lock.json
  client/src/components/Class/Questions/Question.tsx
  client/src/components/Class/Questions/index.tsx
  client/src/components/Class/StudentsPage/style.css
  server/__test__/getTeacherStudents.test.ts
  server/controllers/index.ts
  server/controllers/teacher/getTeacherStudents.ts
  server/controllers/teacher/index.ts
  server/middlewares/teacherAuth.ts
  server/queries/index.ts
  server/queries/teacher/getTeacherStudents.ts
  server/queries/teacher/index.ts
  server/routes/index.ts
  server/routes/teacher.ts
Labels: done

#114 109 put create student studentid health route
  server/controllers/index.ts
  server/controllers/student/index.ts
  server/controllers/student/putStudentHealth.ts
  server/queries/index.ts
  server/queries/students/index.ts
  server/queries/students/putStudentHealthQuery.ts
  server/routes/index.ts
  server/routes/student.ts
Labels: done

#113 107 get create teacher/schedule route
  server/controllers/index.ts
  server/controllers/teacher/getTeacherSchedule.ts
  server/controllers/teacher/index.ts
  server/database/seed/classes.json
  server/queries/getTeacherScheduleQuery.ts
  server/queries/index.ts
  server/routes/teacher.ts
Labels: done

#110 106 get create parent/teachers route
  server/controllers/class/getAssignments.ts
  server/controllers/getParentTeachers.ts
  server/controllers/index.ts
  server/middlewares/parentAuth.ts
  server/middlewares/userAuth.ts
  server/queries/getParentTeachers.ts
  server/queries/index.ts
  server/routes/parent.ts
Labels: done

#140 create profile card
  client/.eslintrc.json
  client/package-lock.json
  client/src/components/ProfileCard/index.tsx
  client/src/components/ProfileCard/style.css
Labels: awaiting-review

#130 get all reports
  server/controllers/index.ts
  server/controllers/profiles/getReports.ts
  server/controllers/profiles/index.ts
  server/database/seed/students.json
  server/database/seed/users.json
  server/middlewares/index.ts
  server/middlewares/studentRelatedToParent.ts
  server/queries/Auth/index.ts
  server/queries/Auth/studentParentRelationQuery.ts
  server/queries/index.ts
  server/queries/profile/getReportsQuery.ts
  server/queries/profile/index.ts
  server/routes/profile.ts
Labels: done

#119 Create feedback component page.
  client/src/App.tsx
  client/src/components/Class/Feedback/Feedback.css
  client/src/components/Class/Feedback/Feedback.tsx
  client/src/components/ClassFeedback/ClassFeedback.css
  client/src/components/ClassFeedback/ClassFeedback.tsx
Labels: awaiting-review

#120 112 get teacher info
  server/__test__/getTeacherInfo.test.ts
  server/controllers/index.ts
  server/controllers/teacher/index.ts
  server/controllers/teacher/teacherInfo.ts
  server/queries/index.ts
  server/queries/teacher/getTeacherInfo.ts
  server/queries/teacher/index.ts
  server/routes/teacher.ts
Labels: done, BACK-END

#111 104 recommended page
  client/src/App.tsx
  client/src/components/AddRecommended.tsx
  client/src/components/style.css
  client/src/pages/index.tsx
  client/src/pages/recommended/RecommendedPage.tsx
  server/__test__/recommended.test.ts
  server/controllers/class/recommended.ts
  server/queries/class/recommendedQueries.ts
Labels: done, FRONT-END

#131 [GET] student health
  server/__test__/profile.test.ts
  server/controllers/index.ts
  server/controllers/profiles/getStudentHealth.ts
  server/controllers/profiles/index.ts
  server/middlewares/healthMiddleware.ts
  server/middlewares/index.ts
  server/queries/index.ts
  server/queries/profile/getStudentHealthsQuery.ts
  server/queries/profile/index.ts
  server/routes/profile.ts
Labels: awaiting-review

#97 Created class announcemtns page.
  client/src/App.tsx
  client/src/components/Class/Announcements/Announcements.css
  client/src/components/Class/Announcements/Announcements.tsx
  client/src/components/Class/ClassDashboard/ClassDashboard.tsx
  server/controllers/class/getTests.ts
  server/controllers/class/index.ts
  server/controllers/index.ts
  server/queries/class/getTestsQuery.ts
  server/queries/class/index.ts
  server/queries/index.ts
  server/routes/class.ts
Labels: done
