Repository CA-G12/GeekSchool, pull requests merged in 2022-11, with the labels that each got.

#137 136 get student tests
  client/src/components/AssignmentModal/index.tsx
  server/__test__/getStudentTest.test.ts
  server/controllers/index.ts
  server/controllers/student/getStudentTests.ts
  server/controllers/student/index.ts
  server/middlewares/index.ts
  server/middlewares/studentAndParent.ts
  server/queries/index.ts
  server/queries/student/getStudentTests.ts
  server/queries/student/index.ts
  server/routes/student.ts
Labels: awaiting-review, BACK-END

#102 Create assignments page
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/AssignmentModal/index.tsx
  client/src/components/Class/Announcements/Announcements.tsx
  client/src/components/Class/Assignments/Assignments.tsx
  client/src/components/Class/ClassDashboard/ClassDashboard.tsx
  client/src/components/Class/Feedback/Feedback.tsx
  client/src/components/Class/Questions/Question.tsx
  client/src/components/Class/cards/AssignmentCards.css
  client/src/components/Class/cards/StudentAssignmentCard.tsx
  client/src/components/Class/cards/TeacherAssignmentCard.tsx
  client/src/components/ClassTests/AddTest/AddTest.tsx
  client/src/interfaces/componentsInterface.ts
  client/src/interfaces/index.ts
  server/controllers/class/getAssignments.ts
  server/queries/class/getStudentTasksQuery.ts
  server/queries/class/teacherAssignmentQuery.ts
  server/routes/student.ts
Labels: awaiting-review

#145 Created student grades section.
  client/src/components/StudentPage/Grades/GradesCollapse/GradesCollapse.css
  client/src/components/StudentPage/Grades/GradesCollapse/GradesCollapse.tsx
  client/src/components/StudentPage/Grades/GradesTable/GradesTable.css
  client/src/components/StudentPage/Grades/GradesTable/GradesTable.tsx
  client/src/components/StudentPage/Grades/StudentGrades.css
  client/src/components/StudentPage/Grades/StudentGrades.tsx
  client/src/interfaces/componentsInterface.ts
  client/src/interfaces/index.ts
Labels: awaiting-review

#146 139 create profile layout
  client/.eslintrc.json
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/ClassFeedback/ClassFeedback.css
  client/src/components/ClassFeedback/ClassFeedback.tsx
  client/src/components/profile/Nav.tsx
  client/src/components/profile/Report.tsx
  client/src/components/profile/ReportCard.tsx
  client/src/components/profile/UserHeader.tsx
  client/src/components/profile/style.css
  client/src/components/style.css
  client/src/interfaces/componentsInterface.ts
  client/src/interfaces/index.ts
  client/src/interfaces/userInterface.ts
  client/src/pages/index.tsx
  client/src/pages/profile/index.tsx
  client/src/pages/profile/style.css
  client/src/style.css
Labels: done

#148 143 teacher schedule
  client/src/components/TeacherSchedule/index.tsx
  client/src/components/TeacherSchedule/style.css
Labels: awaiting-review

#150 144 student calender
  client/package-lock.json
  client/package.json
  client/src/components/Calender/index.tsx
  package-lock.json
  package.json
  server/database/seed/tests.json
Labels: awaiting-review, BACK-END

#135 134 get studentgrades
  server/__test__/getStudentGrades.test.ts
  server/controllers/index.ts
  server/controllers/student/getStudentGrade.ts
  server/controllers/student/index.ts
  server/middlewares/index.ts
  server/middlewares/studentAndParent And teacher.ts
  server/queries/index.ts
  server/queries/student/getStudentGradesQuery.ts
  server/queries/student/index.ts
  server/routes/student.ts
Labels: awaiting-review, BACK-END

#149 Created parent profile page component.
  client/src/App.tsx
  client/src/components/ProfileCard/style.css
  client/src/interfaces/componentsInterface.ts
  client/src/interfaces/index.ts
  client/src/pages/ParentProfile/ParentProfile.css
  client/src/pages/ParentProfile/ParentProfile.tsx
  client/src/pages/index.tsx
  client/src/pages/profile/index.tsx
  client/src/pages/profile/style.css
  server/__test__/profile.test.ts
  server/controllers/profiles/getParentStudent.ts
  server/routes/profile.ts
Labels: done

#153 Created the feedback section of the landing page.
  client/src/assets/user1.png
  client/src/assets/user2.png
  client/src/assets/user3.png
  client/src/pages/LandingPage/LandingFeedback/FeedbackCard/FeedbackCard.css
  client/src/pages/LandingPage/LandingFeedback/FeedbackCard/FeedbackCard.tsx
  client/src/pages/LandingPage/LandingFeedback/LandingFeedback.css
  client/src/pages/LandingPage/LandingFeedback/LandingFeedback.tsx
  client/src/pages/ParentProfile/ParentProfile.tsx
  server/routes/student.ts
Labels: awaiting-review

#154 138 teacher profile
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/ProfileCard/index.tsx
  client/src/components/TeacherStudents/index.tsx
  client/src/components/index.tsx
  client/src/pages/ParentProfile/ParentProfile.tsx
  client/src/pages/index.tsx
  client/src/pages/profile/index.tsx
  client/src/pages/teacherProfile/TeacherProfile.tsx
  package-lock.json
  package.json
  server/controllers/teacher/getTeacherStudents.ts
  server/queries/teacher/getTeacherInfo.ts
  server/queries/teacher/getTeacherStudents.ts
Labels: awaiting-review, BACK-END

#157 152 footer section
  client/src/assets/Map.svg
  client/src/assets/image 20.png
  client/src/assets/left hash.svg
  client/src/assets/right hash.svg
  client/src/pages/FooterSection/index.tsx
  client/src/pages/FooterSection/style.css
Labels: done

#159 Created landing header section
  client/src/assets/GeekSchoolLogo.png
  client/src/assets/landing-bcg.png
  client/src/assets/landing-image.png
  client/src/pages/LandingPage/LandingHeader/LandingHeader.css
  client/src/pages/LandingPage/LandingHeader/LandingHeader.tsx
Labels: awaiting-review

#165 Landingpage
  client/src/App.tsx
  client/src/components/index.tsx
  client/src/components/landingPage/FooterSection/index.tsx
  client/src/components/landingPage/FooterSection/style.css
  client/src/components/landingPage/LandingFeedback/FeedbackCard/FeedbackCard.css
  client/src/components/landingPage/LandingFeedback/FeedbackCard/FeedbackCard.tsx
  client/src/components/landingPage/LandingFeedback/LandingFeedback.css
  client/src/components/landingPage/LandingFeedback/index.tsx
  client/src/components/landingPage/LandingHeader/LandingHeader.css
  client/src/components/landingPage/LandingHeader/index.tsx
  client/src/components/landingPage/StatisticLanding/index.css
  client/src/components/landingPage/StatisticLanding/index.tsx
  client/src/components/landingPage/index.tsx
  client/src/components/landingPage/landingTimeline/index.tsx
  client/src/components/landingPage/landingTimeline/style.css
  client/src/pages/LandingPage/index.tsx
  client/src/pages/index.tsx
Labels: awaiting-review

#164 163 create timeline section for landing page
  client/src/App.tsx
  client/src/assets/bloodPressure.png
  client/src/assets/cancer.png
  client/src/assets/chronic.png
  client/src/assets/dental.png
  client/src/assets/diabetes.png
  client/src/assets/index.tsx
  client/src/assets/other.png
  client/src/assets/vision.png
  client/src/components/healthProfile/HealthProfile.tsx
  client/src/components/healthProfile/style.css
  client/src/components/index.tsx
  client/src/components/landingPage/TimeLineSection.tsx
  client/src/components/landingPage/index.tsx
  client/src/components/landingPage/style.css
  client/src/interfaces/componentsInterface.ts
  client/src/interfaces/index.ts
  client/src/pages/healthProfile/index.tsx
  client/src/pages/healthProfile/style.css
  client/src/pages/index.tsx
  server/middlewares/healthMiddleware.ts
Labels: awaiting-review

#162 Created the readme documentation file of the project
  README.md
Labels: done

#161 158 landing statistic
  client/src/assets/shape.png
  client/src/components/StatisticLanding/index.css
  client/src/components/StatisticLanding/index.tsx
Labels: done, FRONT-END

#167 Edit login signup page
  client/src/components/signUpForm/ParentSignUp.tsx
  client/src/pages/login/index.tsx
  client/src/pages/login/style.css
  client/src/pages/signUp/index.tsx
  client/src/pages/signUp/style.css
  client/src/style.css
  server/controllers/auth/login.ts
  server/utils/validation/userValidation.ts
Labels: awaiting-review

#166 Editing landing page
  client/src/assets/Logo.png
  client/src/assets/new-logo.png
  client/src/components/Class/ClassDashboard/ClassDashboard.tsx
  client/src/components/landingPage/LandingFeedback/FeedbackCard/FeedbackCard.tsx
  client/src/components/landingPage/LandingFeedback/LandingFeedback.css
  client/src/components/landingPage/LandingHeader/LandingHeader.css
  client/src/components/landingPage/LandingHeader/index.tsx
  client/src/components/landingPage/StatisticLanding/index.css
  client/src/components/landingPage/StatisticLanding/index.tsx
  client/src/components/landingPage/landingTimeline/style.css
  client/src/pages/profile/index.tsx
  package-lock.json
Labels: awaiting-review

#169 Edit health card functionality
  client/src/components/TeacherSchedule/index.tsx
  client/src/components/healthProfile/HealthCard.tsx
  client/src/components/landingPage/LandingHeader/index.tsx
  client/src/components/profile/style.css
  client/src/pages/teacherProfile/TeacherProfile.tsx
  client/src/pages/teacherProfile/style.css
  server/controllers/auth/login.ts
  server/queries/teacher/getTeacherInfo.ts
Labels: awaiting-review

#168 update styling for teacher profile
  client/src/components/TeacherSchedule/index.tsx
  client/src/components/TeacherSchedule/style.css
  server/controllers/auth/login.ts
  server/database/seed/users.json
Labels: awaiting-review

#170 Edit health card functionality
  client/src/components/ProfileCard/index.tsx
  client/src/components/ProfileCard/style.css
  client/src/components/TeacherSchedule/index.tsx
  client/src/components/profile/style.css
  client/src/pages/teacherProfile/TeacherProfile.tsx
  client/src/pages/teacherProfile/style.css
  client/src/style.css
Labels: awaiting-review

#171 Student profile connecting and finshing
  client/src/App.tsx
  client/src/components/Student/ClassSection/ClassCard/ClassCard.tsx
  client/src/components/Student/ClassSection/ClassSection.css
  client/src/components/Student/ClassSection/ClassSection.tsx
  client/src/components/Student/Grades/GradesCollapse/GradesCollapse.css
  client/src/components/Student/Grades/GradesCollapse/GradesCollapse.tsx
  client/src/components/Student/Grades/GradesTable/GradesTable.css
  client/src/components/Student/Grades/GradesTable/GradesTable.tsx
  client/src/components/Student/Grades/StudentGrades.css
  client/src/components/Student/Grades/StudentGrades.tsx
  client/src/components/TeacherSchedule/index.tsx
  client/src/components/healthProfile/style.css
  client/src/components/profile/Report.tsx
  client/src/components/profile/style.css
  client/src/interfaces/componentsInterface.ts
  client/src/pages/healthProfile/index.tsx
  client/src/pages/profile/index.tsx
  client/src/pages/studentProfile/index.tsx
  client/src/pages/teacherProfile/style.css
  server/database/seed/classStudent.json
  server/database/seed/classes.json
Labels: awaiting-review

#172 Fix teacher student parent bugs
  client/src/components/Class/ClassDashboard/ClassDashboard.tsx
  client/src/components/ProfileCard/index.tsx
  client/src/components/ProfileCard/style.css
  client/src/components/TeacherSchedule/index.tsx
  client/src/components/profile/Report.tsx
  client/src/components/profile/style.css
  client/src/pages/ParentProfile/ParentProfile.tsx
  client/src/pages/healthProfile/index.tsx
  client/src/pages/profile/index.tsx
  client/src/pages/studentProfile/index.tsx
  client/src/pages/teacherProfile/TeacherProfile.tsx
  client/src/pages/teacherProfile/style.css
Labels: done

#173 Singup fixing
  .gitignore
  client/src/pages/signUp/index.tsx
  server/controllers/auth/signup.ts
Labels: awaiting-review

#175 Create logout function
  client/src/App.tsx
  client/src/components/Class/ClassDashboard/ClassDashboard.tsx
  client/src/pages/profile/index.tsx
  client/src/pages/profile/style.css
Labels: awaiting-review

#176 178 Edit context
  client/src/App.tsx
  client/src/components/Class/ClassDashboard/ClassDashboard.tsx
  client/src/context/AuthContext/index.tsx
  client/src/interfaces/userInterface.ts
  client/src/pages/ParentProfile/ParentProfile.tsx
  client/src/pages/login/index.tsx
  client/src/pages/signUp/index.tsx
  client/src/pages/teacherProfile/TeacherProfile.tsx
  server/database/seed/users.json
Labels: done

#179 Edit parent signup
  client/src/components/landingPage/LandingHeader/index.tsx
  client/src/components/signUpForm/ParentSignUp.tsx
  client/src/context/AuthContext/index.tsx
  client/src/interfaces/userInterface.ts
  client/src/pages/ParentProfile/ParentProfile.tsx
  client/src/pages/signUp/index.tsx
  server/controllers/auth/signup.ts
  server/controllers/index.ts
  server/controllers/student/getIfStudentUserExists.ts
  server/controllers/student/index.ts
  server/queries/studentQueries.ts
  server/routes/student.ts
Labels: done

#181 Edit seed data.
  server/__test__/addNewAssignment.test.ts
  server/__test__/addNewFeedback.test.ts
  server/__test__/classFeedback.test.ts
  server/__test__/getTeacherInfo.test.ts
  server/__test__/login.test.ts
  server/database/seed/announcements.json
  server/database/seed/assignmentStudent.json
  server/database/seed/assignments.json
  server/database/seed/classStudent.json
  server/database/seed/classes.json
  server/database/seed/feedbacks.json
  server/database/seed/health.json
  server/database/seed/parents.json
  server/database/seed/questions.json
  server/database/seed/recommendations.json
  server/database/seed/reports.json
  server/database/seed/schedules.json
  server/database/seed/students.json
  server/database/seed/teachers.json
  server/database/seed/testStudent.json
  server/database/seed/tests.json
  server/database/seed/users.json
  server/queries/teacher/getTeacherInfo.ts
Labels: done

#183 edits on landing page style related to #182
  client/src/components/landingPage/FooterSection/index.tsx
  client/src/components/landingPage/FooterSection/style.css
  client/src/components/landingPage/LandingFeedback/FeedbackCard/FeedbackCard.css
  client/src/components/landingPage/LandingFeedback/FeedbackCard/FeedbackCard.tsx
  client/src/components/landingPage/LandingFeedback/LandingFeedback.css
  client/src/components/landingPage/LandingFeedback/index.tsx
  client/src/components/landingPage/LandingHeader/LandingHeader.css
  client/src/components/landingPage/LandingHeader/index.tsx
  client/src/components/landingPage/StatisticLanding/index.css
  client/src/components/landingPage/landingTimeline/index.tsx
  client/src/components/landingPage/landingTimeline/style.css
  client/src/pages/LandingPage/index.tsx
  server/controllers/student/getIfStudentUserExists.ts
Labels: done

#184 Edit teacher rout
  client/src/pages/ParentProfile/ParentProfile.tsx
  client/src/pages/teacherProfile/TeacherProfile.tsx
  server/controllers/teacher/teacherInfo.ts
  server/queries/teacher/getTeacherInfo.ts
Labels: done

#186 Modify dashboard style
  client/src/components/Class/Feedback/Feedback.css
  client/src/components/Class/Questions/index.tsx
  client/src/components/Class/Questions/style.css
  client/src/components/Class/StudentsPage/index.tsx
  client/src/components/style.css
  client/src/context/AuthContext/index.tsx
  client/src/pages/login/index.tsx
  client/src/pages/recommended/RecommendedPage.tsx
  client/src/pages/signUp/index.tsx
  client/src/pages/studentProfile/index.tsx
  client/src/pages/teacherProfile/TeacherProfile.tsx
  server/controllers/student/getStudentInfo.ts
  server/middlewares/studentInfoMiddleware.ts
  server/middlewares/userAuth.ts
  server/routes/student.ts
Labels: awaiting-review

#191 190 fix student profile bugs
  client/README.md
  client/public/index.html
  client/src/App.tsx
  client/src/components/Calender/index.tsx
  client/src/components/Calender/style.css
  client/src/components/Student/ClassSection/ClassSection.tsx
  client/src/components/Student/Grades/GradesCollapse/GradesCollapse.css
  client/src/components/Student/Grades/StudentGrades.css
  client/src/components/profile/Report.tsx
  client/src/context/AuthContext/index.tsx
  client/src/pages/login/index.tsx
  client/src/pages/signUp/index.tsx
  client/src/pages/studentProfile/index.tsx
  client/src/pages/teacherProfile/TeacherProfile.tsx
  server/controllers/student/getStudentClasses.ts
  server/controllers/student/getStudentInfo.ts
  server/middlewares/studentRelatedToParent.ts
  server/middlewares/userAuth.ts
  server/routes/student.ts
Labels: done

#193 192 post report
  client/src/components/profile/Report.tsx
  server/controllers/index.ts
  server/controllers/student/index.ts
  server/controllers/student/postStudentReports.ts
  server/middlewares/teacherAuth.ts
  server/queries/index.ts
  server/queries/student/index.ts
  server/queries/student/postStudentReportsQuery.ts
  server/routes/student.ts
Labels: done

#105 87 create admin statistics page
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/Class/cards/DashboardCard.tsx
  client/src/components/Class/cards/index.ts
  client/src/components/profile/Report.tsx
  client/src/context/AuthContext/index.tsx
  client/src/interfaces/index.ts
  client/src/interfaces/pageInterfaces.tsx
  client/src/pages/index.tsx
  client/src/pages/login/index.tsx
  client/src/pages/statisticsPage/index.tsx
  client/src/pages/statisticsPage/style.css
  server/controllers/class/getStats.ts
  server/controllers/index.ts
  server/controllers/student/postStudentReports.ts
  server/queries/index.ts
  server/queries/student/postStudentReportsQuery.ts
  server/routes/class.ts
  server/routes/student.ts
Labels: awaiting-review

#195 194 fix profile pages bugs
  client/src/context/AuthContext/index.tsx
  client/src/pages/ParentProfile/ParentProfile.tsx
  client/src/pages/login/index.tsx
  client/src/pages/studentProfile/index.tsx
  client/src/pages/teacherProfile/TeacherProfile.tsx
  server/queries/student/getStudentInfoQuery.ts
Labels: done

#198 197 edit view profile and logout in profile page
  client/src/components/Class/ClassDashboard/ClassDashboard.tsx
  client/src/components/Class/ClassDashboard/style.css
  client/src/components/ProfileCard/index.tsx
  client/src/components/ProfileCard/style.css
  client/src/components/profile/Report.tsx
  client/src/pages/profile/index.tsx
  client/src/pages/profile/style.css
  server/controllers/student/postStudentReports.ts
Labels: done

#201 200 edit landingpage and create new section
  client/src/App.tsx
  client/src/assets/GeekSchoolLogo.png
  client/src/assets/avatar.png
  client/src/assets/card1.jpg
  client/src/assets/card2.jpg
  client/src/assets/card3.jpg
  client/src/assets/image 20.png
  client/src/assets/index.tsx
  client/src/assets/landing-image.png
  client/src/components/ProfileCard/index.tsx
  client/src/components/QuestionsCard.tsx
  client/src/components/index.tsx
  client/src/components/landingPage/FooterSection/index.tsx
  client/src/components/landingPage/FooterSection/style.css
  client/src/components/landingPage/LandingCard/index.tsx
  client/src/components/landingPage/LandingCard/style.css
  client/src/components/landingPage/LandingFeedback/FeedbackCard/FeedbackCard.css
  client/src/components/landingPage/LandingHeader/LandingHeader.css
  client/src/components/landingPage/LandingHeader/index.tsx
  client/src/components/landingPage/StatisticLanding/index.css
  client/src/components/landingPage/StatisticLanding/index.tsx
  client/src/components/landingPage/index.tsx
  client/src/context/AuthContext/index.tsx
  client/src/pages/LandingPage/index.tsx
  client/src/pages/ParentProfile/ParentProfile.tsx
  client/src/pages/studentProfile/index.tsx
  client/src/pages/teacherProfile/TeacherProfile.tsx
  server/controllers/profiles/getTeachersClasses.ts
  server/queries/profile/getClassQuery.ts
  server/queries/profile/getTeacherClassesQuery.ts
  server/queries/profile/index.ts
Labels: done

#206 205 page 404
  client/src/App.tsx
  client/src/components/landingPage/LandingCard/index.tsx
  client/src/pages/notFoundPage/index.tsx
Labels: done

#209 207 class pages edits
  client/src/App.tsx
  client/src/components/AddRecommended.tsx
  client/src/components/AssignmentModal/index.css
  client/src/components/AssignmentModal/index.tsx
  client/src/components/Class/Assignments/Assignments.css
  client/src/components/Class/Assignments/Assignments.tsx
  client/src/components/Class/ClassDashboard/ClassDashboard.tsx
  client/src/components/Class/ClassDashboard/style.css
  client/src/components/Class/Feedback/Feedback.css
  client/src/components/Class/Feedback/Feedback.tsx
  client/src/components/Class/Grades/index.tsx
  client/src/components/Class/Questions/AnsweredQuestion.tsx
  client/src/components/Class/Questions/index.tsx
  client/src/components/Class/Questions/style.css
  client/src/components/Class/StudentsPage/index.tsx
  client/src/components/Class/StudentsPage/style.css
  client/src/components/Class/cards/AssignmentCards.css
  client/src/components/Class/cards/StudentAssignmentCard.tsx
  client/src/components/Class/cards/TeacherAssignmentCard.tsx
  client/src/components/ClassTests/AddTest/AddTest.tsx
  client/src/components/Student/ClassSection/ClassCard/ClassCard.tsx
  client/src/components/style.css
  client/src/pages/notFoundPage/index.tsx
  client/src/pages/recommended/RecommendedPage.tsx
  client/src/pages/recommended/style.css
  client/src/pages/statisticsPage/index.tsx
  client/src/pages/statisticsPage/style.css
  client/src/style.css
  server/controllers/class/getClassQuestions.ts
  server/controllers/class/recommended.ts
  server/queries/class/getClassQuestionsQuery.ts
  server/queries/class/recommendedQueries.ts
  server/routes/class.ts
Labels: done

#212 211 parent profile
  client/package-lock.json
  client/package.json
  client/src/components/ProfileCard/index.tsx
  client/src/components/ProfileCard/style.css
  client/src/pages/ParentProfile/ParentProfile.tsx
  server/controllers/getParentTeachers.ts
  server/controllers/profiles/getParentStudent.ts
Labels: done

#224 edited signup route functionality and create new query thats update p…
  server/controllers/auth/signup.ts
  server/models/index.ts
  server/models/student.ts
  server/queries/index.ts
  server/queries/student/index.ts
  server/queries/student/putParentIdForStudentQuery.ts
  server/queries/studentQueries.ts
Labels: done

#226 225 edit health functionality
  client/src/components/Student/ClassSection/ClassSection.tsx
  client/src/components/Student/Grades/StudentGrades.tsx
  client/src/pages/healthProfile/index.tsx
  client/src/pages/profile/index.tsx
  server/controllers/auth/signup.ts
  server/controllers/profiles/getStudentHealth.ts
  server/controllers/student/getStudentClasses.ts
  server/controllers/student/putStudentHealth.ts
  server/queries/index.ts
  server/queries/profile/getStudentHealthsQuery.ts
  server/queries/student/addStudentHealthQuery.ts
  server/queries/student/index.ts
  server/routes/profile.ts
Labels: done

#230 229 edit timeline section style
  client/src/components/landingPage/LandingHeader/LandingHeader.css
  client/src/components/landingPage/LandingHeader/index.tsx
  client/src/components/landingPage/landingTimeline/index.tsx
  client/src/components/landingPage/landingTimeline/style.css
  client/src/components/landingPage/landingTimeline/timeLineData.ts
Labels: done

#234 233 create class chat
  client/package-lock.json
  client/package.json
  client/src/components/AddStudentModal.tsx
  client/src/components/Class/Chat/ChatMessage.tsx
  client/src/components/Class/Chat/index.tsx
  client/src/components/Class/Chat/style.css
  client/src/components/Class/ClassDashboard/ClassDashboard.tsx
  client/src/components/ProfileCard/index.tsx
  client/src/context/AuthContext/index.tsx
  client/src/interfaces/chat.tsx
  client/src/interfaces/userInterface.ts
  client/src/pages/ParentProfile/ParentProfile.tsx
  package-lock.json
  package.json
  server/IOHandler/IoHandler.ts
  server/__test__/addAnnouncement.test.ts
  server/app.ts
  server/controllers/auth/login.ts
  server/controllers/auth/signup.ts
  server/controllers/index.ts
  server/controllers/student/index.ts
  server/controllers/student/putParentIdForStudent.ts
  server/index.ts
  server/models/index.ts
  server/queries/chat/getMessageQuery.ts
  server/queries/index.ts
  server/routes/student.ts
  server/utils/interfaces/payloadInterface.ts
Labels: done

#236 Edit chat style
  client/src/components/Class/Chat/index.tsx
  client/src/components/Class/Chat/style.css
  client/src/components/Class/ClassDashboard/style.css
  client/src/style.css
Labels: done

#240 239 edit loading bugs
  client/src/assets/شعار_كأس_العالم_قطر_2022.svg.webp
  client/src/components/Class/Assignments/Assignments.tsx
  client/src/components/Class/Chat/index.tsx
  client/src/components/Class/Chat/style.css
  client/src/components/Class/ClassDashboard/style.css
  client/src/components/Class/Feedback/Feedback.tsx
  client/src/components/Class/Questions/index.tsx
  client/src/components/Class/Questions/style.css
  client/src/components/Class/StudentsPage/index.tsx
  client/src/components/Class/cards/DashboardCard.tsx
  client/src/pages/ParentProfile/ParentProfile.tsx
  client/src/pages/profile/index.tsx
  client/src/pages/recommended/RecommendedPage.tsx
  client/src/pages/statisticsPage/index.tsx
  client/src/pages/studentProfile/index.tsx
  client/src/pages/teacherProfile/TeacherProfile.tsx
Labels: done
